#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32GB
#SBATCH --gres=gpu:1
#SBATCH --constraint=rtx3090
#SBATCH --time=1-00:00:00
#SBATCH --job-name=pretrain_shift_additional_loss
#SBATCH --output=O-%x.%j.out
#SBATCH --error=E-%x.%j.err

cd /scratch/mbikandi/outlier-detection

source /scratch/mbikandi/.bashrc
source activate dev2

python3 pretrain_shift_additional_loss.py
